Ride service & docker
KiryaHandsome/cab-aggregator pull request #3
Opened 2023-11-16 21:13 UTC by KiryaHandsome

Implement next features:

- Ride service REST api and OpenApi docs
- Communication between ride and driver services using kafka
- Dockerfiles for services and docker compose for deploying infrastructure

2023-11-20 18:33 UTC, AbandonedScope requested changes

2023-11-20 18:33 UTC, AbandonedScope commented on driver/Dockerfile
https://spring.io/guides/topicals/spring-boot-docker/#:~:text=with%20other%20applications.-,A%20Better%20Dockerfile,-A%20Spring%20Boot

2023-11-20 18:33 UTC, AbandonedScope commented on driver/src/main/java/com/modsen/driver/consumer/KafkaListeners.java
Хочу, чтобы ты реализовал это не через Spring Kafka, а через Spring Integration

2023-11-20 18:33 UTC, AbandonedScope commented on driver/src/main/java/com/modsen/driver/service/impl/RandomDriverPicker.java
> +    public DriverResponse pickAvailable() {
Наверно, логично передfвать сюда `RideOrdered`, чтобы была хоть видимость, что мы как-то выбираем Driver-a, + может потом придумаешь реализацию, где эта инфа действительно нужна

2023-11-20 18:33 UTC, AbandonedScope commented on driver/src/main/java/com/modsen/driver/service/impl/RandomDriverPicker.java
> +                .orElseThrow(() -> new NoAvailableDriversException("Driver not found"));
А если driver уже `BUSY`?

2023-11-20 18:33 UTC, AbandonedScope commented on driver/src/main/java/com/modsen/driver/service/impl/RideExecutorStub.java
Думаю, этому здесь не место  - логика управления поездками должна была быть в самом rides-service, и, думаю, что нужно было там реализовать эндпоинты по началу и окончанию поездки

2023-11-20 18:33 UTC, AbandonedScope commented on passenger/Dockerfile
[A Better Dockerfile](https://spring.io/guides/topicals/spring-boot-docker/#:~:text=with%20other%20applications.-,A%20Better%20Dockerfile,-A%20Spring%20Boot)

2023-11-20 18:33 UTC, AbandonedScope commented on ride/Dockerfile
https://spring.io/guides/topicals/spring-boot-docker/#:~:text=with%20other%20applications.-,A%20Better%20Dockerfile,-A%20Spring%20Boot

2023-11-20 18:33 UTC, AbandonedScope commented on ride/pom.xml
> +                <version>3.11.0</version>
Выноси в properties

2023-11-20 18:33 UTC, AbandonedScope commented on ride/src/main/java/com/modsen/ride/exception/GlobalExceptionHandler.java
> +        ErrorResponse errorResponse = new ErrorResponse(500, ex.getMessage() + Arrays.toString(ex.getStackTrace()));
500? - не константа?

2023-11-20 18:33 UTC, AbandonedScope commented on ride/src/main/java/com/modsen/ride/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<?> handleRuntime(RuntimeException ex) {
Обрабатываешь вообще всё одним методом?

2023-11-20 18:33 UTC, AbandonedScope commented on ride/src/main/java/com/modsen/ride/model/Ride.java
> +    private String id;
@GeneratedValue

2023-11-21 09:41 UTC, KiryaHandsome commented on driver/src/main/java/com/modsen/driver/service/impl/RideExecutorStub.java
> Думаю, этому здесь не место - логика управления поездками должна была быть в самом rides-service, и, думаю, что нужно было там реализовать эндпоинты по началу и окончанию поездки

Тогда кафка будет использоваться всего в 1 случае(при новом запросе на поездку). Ничего страшного?

2023-11-21 09:51 UTC, KiryaHandsome commented on ride/src/main/java/com/modsen/ride/model/Ride.java
> +    private String id;
> @GeneratedValue

Это модель для mongodb

2023-11-21 14:26 UTC, AbandonedScope approved these changes

2023-11-21 14:47 UTC, merged