Unit & Integration tests
KiryaHandsome/cab-aggregator pull request #4
Opened 2023-11-27 21:58 UTC by KiryaHandsome

Unit and integration tests for Driver and Passenger services

2023-11-29 09:42 UTC, AbandonedScope requested changes

2023-11-29 09:42 UTC, AbandonedScope commented on driver/src/main/java/com/modsen/driver/service/impl/DriverServiceImpl.java
> +        mapper.updateIfNotNull(request, driver);
лучше переименнуй на что-то вроде `mapIfNotNull`

2023-11-29 09:42 UTC, AbandonedScope commented on driver/src/test/java/com/modsen/driver/integration/controller/DriverControllerIntegrationTest.java
> +                .statusCode(HttpStatus.OK.value());
Вынеси логику формирования и отправки запроса в отдельный класс(что-нибудь вроде DriverTestClient), создай там методы ответственные за каждый случай и просто вызывай их, так сам код внутри тестов будет белее читаемым
P.s. Проверка соответствия полей (`is(expected. ....`) - не должна будут быть в DriverTestClient, он ответственен только за отправку запроса. Чтобы получить сущность можно вызвать - 
```
...
.then()
...
.extract()
.as(Driver...Response.class);
```

2023-11-29 09:42 UTC, AbandonedScope commented on driver/src/test/java/com/modsen/driver/mapper/DriverMapperTest.java
> +    }
Почему перед каждым тестом?

2023-11-29 09:42 UTC, AbandonedScope commented on driver/src/test/java/com/modsen/driver/mapper/DriverMapperTest.java
> +        assertThat(actual.getStatus()).isEqualTo(Status.OFFLINE);
Обычно не рекомендуется делать больше одно ассерта на тест - лучше сформируй сам объект и срани их, а не отдельно каждое поле

2023-11-29 09:42 UTC, AbandonedScope commented on driver/src/test/java/com/modsen/driver/util/HostUtil.java
> +    }
А чего так, а не полем?

2023-11-29 09:42 UTC, AbandonedScope commented on passenger/src/main/java/com/modsen/passenger/dto/request/PassengerCreate.java
>      @NotNull(message = "Name must not be null")
Вообще, эти сообщения лучше подтягивать из файла, чтобы их можно было локализовать/изменить без изменения в коде

2023-11-29 09:42 UTC, AbandonedScope commented on passenger/src/test/resources/application.yaml
Что-то у тебя этот файл(и в целом resources) немного не там лежит

2023-11-29 09:42 UTC, AbandonedScope commented on ride/src/main/resources/application.yaml
В чём разница между эти файлом и application-docker.yaml?

2023-11-29 13:29 UTC, KiryaHandsome commented on ride/src/main/resources/application.yaml
Хосты разные у mongo и kafka. По умолчанию стоит localhost

2023-11-29 13:33 UTC, KiryaHandsome commented on driver/src/test/java/com/modsen/driver/util/HostUtil.java
> +    }
В будущем можно будет реализовать ее и брать не статические значения, а по определенной тестовой среде.

2023-11-29 13:41 UTC, KiryaHandsome commented on passenger/src/test/resources/application.yaml
Это ведь ресурсы для тестов. Где они должны лежать?

2023-11-29 13:56 UTC, AbandonedScope commented on passenger/src/test/resources/application.yaml
Сорри, показалось что в main нет папки с ресурсами

2023-11-29 13:59 UTC, AbandonedScope commented on ride/src/main/resources/application.yaml
Это делается иначе
Когда ты запускаешь что-то в докере, ты передаёшь эти параметры(пути и тд) как переменный среды

2023-11-30 09:20 UTC, AbandonedScope commented on driver/src/test/java/com/modsen/driver/integration/controller/DriverControllerIT.java
> +                .as(DriverResponse.class);
Это тоже оставь в driverTestClient - просто сделай несколько методов, один - когда всё окей(`... .as(DriverResponse.class)`), второй - когда есть ошибка (`... .as(ErrorResponse.class)`) и третий, когда ошибка валидации(`... .as(ValidationErrorResponse.class)`) и тд

2023-11-30 17:53 UTC, AbandonedScope requested changes

2023-11-30 17:53 UTC, AbandonedScope commented on passenger/src/main/java/com/modsen/passenger/exception/GlobalExceptionHandler.java
> +                .map(m -> messageSource.getMessage(m, new Object[0], LocaleContextHolder.getLocale()))
Вместо `new Object[0]` можно просто `null` передать
[Вот ссылка на документацию](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/MessageSource.html#:~:text=ensuring%20maximum%20clarity.-,args%20%2D%20an%20array%20of%20arguments%20that%20will%20be%20filled%20in%20for%20params%20within%20the%20message%20(params%20look%20like%20%22%7B0%7D%22%2C%20%22%7B1%2Cdate%7D%22%2C%20%22%7B2%2Ctime%7D%22%20within%20a%20message)%2C%20or%20null%20if%20none,-defaultMessage%20%2D%20a%20default)

2023-11-30 18:02 UTC, AbandonedScope approved these changes

2023-11-30 18:04 UTC, merged